# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Classification.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import qApp
import re


class Ui_MainWindow(object):
    def __init__(self):
        self.numberLayers = ""
        self.two_layer = '75872'
        self.four_layer = '68725'
        self.six_layer = '68726'

        super().__init__()

        self.setupUi(MainWindow)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 750)
        MainWindow.setMinimumSize(QtCore.QSize(1050, 750))
        MainWindow.setMaximumSize(QtCore.QSize(1050, 750))
        MainWindow.setStatusTip("Hello =)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 521, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_numberClassification = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_numberClassification.setObjectName("label_numberClassification")
        self.horizontalLayout.addWidget(self.label_numberClassification)
        self.lineEditNumberClassification = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditNumberClassification.setStatusTip("Number classification")
        self.lineEditNumberClassification.setObjectName("lineEditNumberClassification")
        self.horizontalLayout.addWidget(self.lineEditNumberClassification)
        self.comboBox_layers = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_layers.setGeometry(QtCore.QRect(20, 60, 120, 20))
        self.comboBox_layers.setStatusTip("Select layers")
        self.comboBox_layers.setObjectName("comboBox_layers")
        self.comboBox_layers.addItem("")
        self.comboBox_layers.addItem("")
        self.comboBox_layers.addItem("")
        self.comboBox_layers.activated[str].connect(self.SelectLayers)
        self.comboBox_thickness = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_thickness.setGeometry(QtCore.QRect(146, 60, 333, 20))
        self.comboBox_thickness.setStatusTip("Select thickness")
        self.comboBox_thickness.setObjectName("comboBox_thickness")
        self.comboBox_thickness.addItem("")
        self.comboBox_thickness.addItem("")
        self.comboBox_thickness.addItem("")
        self.comboBox_thickness.addItem("")
        self.comboBox_thickness.addItem("")
        self.comboBox_thickness.addItem("")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 620, 320, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonConnectDB = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonConnectDB.setObjectName("pushButtonConnectDB")
        self.gridLayout.addWidget(self.pushButtonConnectDB, 0, 1, 1, 1)
        self.pushButtonInsertDB = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonInsertDB.setObjectName("pushButtonInsertDB")
        self.gridLayout.addWidget(self.pushButtonInsertDB, 0, 2, 1, 1)
        self.pushButtonCreateDB = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonCreateDB.setObjectName("pushButtonCreateDB")
        self.gridLayout.addWidget(self.pushButtonCreateDB, 0, 0, 1, 1)
        self.pushButtonSelectDB = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonSelectDB.setObjectName("pushButtonSelectDB")
        self.gridLayout.addWidget(self.pushButtonSelectDB, 0, 3, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 560, 1011, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_enterManually = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_enterManually.setObjectName("label_enterManually")
        self.horizontalLayout_5.addWidget(self.label_enterManually)
        self.lineEditManually_layers = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEditManually_layers.setObjectName("lineEditManually_layers")
        self.horizontalLayout_5.addWidget(self.lineEditManually_layers)
        self.lineEditManually_thickness = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEditManually_thickness.setObjectName("lineEditManually_thickness")
        self.horizontalLayout_5.addWidget(self.lineEditManually_thickness)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_5.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_5.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_5.addWidget(self.lineEdit_6)
        self.label_layers = QtWidgets.QLabel(self.centralwidget)
        self.label_layers.setGeometry(QtCore.QRect(170, 540, 47, 13))
        self.label_layers.setObjectName("label_layers")
        self.label_thickness = QtWidgets.QLabel(self.centralwidget)
        self.label_thickness.setGeometry(QtCore.QRect(350, 540, 47, 13))
        self.label_thickness.setObjectName("label_thickness")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(520, 540, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(700, 540, 47, 13))
        self.label_5.setObjectName("label_5")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 670, 331, 23))
        self.progressBar.setProperty("value", 50)
        self.progressBar.setObjectName("progressBar")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(19, 89, 1011, 441))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonShowData = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonShowData.setObjectName("pushButtonShowData")
        self.gridLayout_2.addWidget(self.pushButtonShowData, 1, 0, 1, 1)
        self.tableWidgetFromInsertDB = QtWidgets.QTableWidget(self.gridLayoutWidget_2)
        self.tableWidgetFromInsertDB.setRowCount(15)
        self.tableWidgetFromInsertDB.setColumnCount(15)
        self.tableWidgetFromInsertDB.setObjectName("tableWidgetFromInsertDB")
        self.gridLayout_2.addWidget(self.tableWidgetFromInsertDB, 0, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(710, 0, 333, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_user = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_user.setMaximumSize(QtCore.QSize(330, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_user.setFont(font)
        self.label_user.setObjectName("label_user")
        self.verticalLayout_2.addWidget(self.label_user)
        self.label_rightsUser = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_rightsUser.setMaximumSize(QtCore.QSize(330, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_rightsUser.setFont(font)
        self.label_rightsUser.setObjectName("label_rightsUser")
        self.verticalLayout_2.addWidget(self.label_rightsUser)
        self.pushButtonUserRegistration = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonUserRegistration.setGeometry(QtCore.QRect(910, 60, 129, 23))
        self.pushButtonUserRegistration.setObjectName("pushButtonUserRegistration")
        self.pushButtonUserAuthorization = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonUserAuthorization.setGeometry(QtCore.QRect(570, 10, 129, 23))
        self.pushButtonUserAuthorization.setObjectName("pushButtonUserAuthorization")
        self.textEditConsoleInformation = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditConsoleInformation.setGeometry(QtCore.QRect(363, 620, 670, 80))
        self.textEditConsoleInformation.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEditConsoleInformation.setObjectName("textEditConsoleInformation")
        self.label_consoleInformation = QtWidgets.QLabel(self.centralwidget)
        self.label_consoleInformation.setGeometry(QtCore.QRect(620, 600, 101, 16))
        self.label_consoleInformation.setObjectName("label_consoleInformation")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(910, 540, 47, 13))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAuthor = QtWidgets.QAction(MainWindow)
        self.actionAuthor.setObjectName("actionAuthor")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionAuthor)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.CreateBDSQLite3()
        self.OutConsoleLog("User is: " + os.getlogin())


    def retranslateUi(self, MainWindow):
        self.username = self.Get_username()

        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ClassificationBD"))
        self.label_numberClassification.setText(_translate("MainWindow", "number"))
        self.comboBox_layers.setItemText(0, _translate("MainWindow", "2-слойные"))
        self.comboBox_layers.setItemText(1, _translate("MainWindow", "4-слойные"))
        self.comboBox_layers.setItemText(2, _translate("MainWindow", "6 и более слойные"))
        self.comboBox_thickness.activated[str].connect(self.ParseClassifications)
        self.pushButtonConnectDB.setText(_translate("MainWindow", "Connect DB"))
        self.pushButtonInsertDB.setText(_translate("MainWindow", "Insert DB"))
        self.pushButtonCreateDB.setText(_translate("MainWindow", "Create DB"))
        self.pushButtonSelectDB.setText(_translate("MainWindow", "Select DB"))
        self.label_enterManually.setText(_translate("MainWindow", "Enter manually"))
        self.label_layers.setText(_translate("MainWindow", "Layers"))
        self.label_thickness.setText(_translate("MainWindow", "Thickness"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.pushButtonShowData.setText(_translate("MainWindow", "Show Data"))
        self.label_user.setText(_translate("MainWindow", "User:  " + self.username))
        self.label_rightsUser.setText(_translate("MainWindow", "Rights: company member"))
        self.pushButtonUserRegistration.setText(_translate("MainWindow", "User registration"))
        self.pushButtonUserAuthorization.setText(_translate("MainWindow", "Authorization"))
        self.label_consoleInformation.setText(_translate("MainWindow", "Console information"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAuthor.setText(_translate("MainWindow", "Author"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

        self.actionExit.setStatusTip("Exit application")
        self.actionExit.triggered.connect(qApp.quit)

    def SelectLayers(self, text):
        ''' 1) Функция, которая активируется при выборе кол-ва слоев платы.
            Сохраняет перменную для открытыя парсинга файлика '''

        if (text == self.comboBox_layers.itemText(0)):
            ''' 2) '''
            self.numberLayers = '75872'
            self.SelectThickness(self.numberLayers)

        elif (text == self.comboBox_layers.itemText(1)):
            self.numberLayers = '68725'
            self.SelectThickness(self.numberLayers)

        elif (text == self.comboBox_layers.itemText(2)):
            self.numberLayers = '68726'
            self.SelectThickness(self.numberLayers)

        else:
            self.numberLayers = ''

    def SelectThickness(self, text):
        self.comboBox_thickness.clear()  # при каждом изменении кол-ва слоев список обновляется
        if (text == self.two_layer):
            self.comboBox_thickness.addItems(["До 20 включ.",
                                              "Свыше 20 до 30 включ.", "Свыше 30 до 50 включ.",
                                              "Свыше 50 до 80 включ.", "Свыше 80 до 125 включ.",
                                              "Свыше 125 до 200 включ.", "Свыше 200"])

        elif (text == self.four_layer):
            self.comboBox_thickness.addItems(["До 20 мм вкл.",
                                              "Св. 20 до 50 мм вкл.", "Св.50 до 125 мм вкл.",
                                              "Св. 125 до 200 мм вкл.", "Св. 200 до 400 мм вкл.",
                                              "Св. 400 мм"])

        elif (text == self.six_layer):
            self.comboBox_thickness.addItems(["До 20 мм вкл.",
                                              "Св. 20 до 50 мм вкл.", "Св. 50 до 125 мм вкл.",
                                              "Св. 125 до 200 мм вкл.", "Св. 200 до 400 мм вкл.",
                                              "Св. 400 мм"])

        else:
            self.comboBox_thickness.clear()

    def ParseClassifications(self, text):

        if (self.numberLayers == '75872'):
            file = open('script75_den.js', 'r', -1)
            # self.textEditConsoleInformation.setText("Open file: script75_den.js")
            self.OutConsoleLog("Open file: script75_den.js")
        elif (self.numberLayers == '68725' or self.numberLayers == '68726'):
            file = open('script68_den.js', 'r', -1)
            # self.textEditConsoleInformation.setText("Open file: script68_den.js")
            self.OutConsoleLog("Open file: script68_den.js")
        else:
            # self.textEditConsoleInformation.setText("ERROR!!!" + "\n" + "Select the number of layers")
            self.OutConsoleLog("ERROR!!!" + "\n" + "Select the number of layers")

        if (self.numberLayers != ""):
            data = file.read()
            for line in data.split('\n'):
                if re.findall(r'^\[\'' + self.numberLayers + '\d+\', \'' + text, line):
                    resultNumberComponent = re.findall(r'^\[\'(' + self.numberLayers + '\d+)\', \'' + text, line)[0]
                    # print(line)
                    # print(resultNumberComponent)
            file.close()

            self.lineEditNumberClassification.setText(resultNumberComponent)
        return 0

    def Get_username(self):
        return os.getlogin()

    def CreateBDSQLite3 (self):
        self.OutConsoleLog(os.getcwd())
        if not os.path.exists(os.getcwd() + "\DataBase\SQLite3"):
            os.mkdir(os.getcwd() + "\DataBase")
            os.mkdir(os.getcwd() + "\DataBase\SQLite3")
        conn = sqlite3.connect(r"DataBase\SQLite3\mydatabase.db")

    def OutConsoleLog (self, text):
        self.textEditConsoleInformation.append(str(text)+"\n\n")

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
